# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches:
    - main
    - staging
    - develop
  pull_request:
    # branches:
    # - main
    # - staging
    # - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # Docker hub
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # -
      #   name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Setup Repos
        run: |
          mkdir -p zz-build
          cp -a * zz-build/backend/ | true
          git clone git@github.com:TheBitGram/core.git zz-build/core

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: zz-build/backend/Dockerfile
          tag_with_ref: true
          push: true
          tags: |
            067550988196.dkr.ecr.us-east-1.amazonaws.com/frontend:${{ github.sha }}
            067550988196.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  # Deploy to dev
  # deploy-dev:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Commit change to the dev tags
